siteTitle = "Go7hic"
siteDescr = ""
siteAuthor = "Go7hic"

siteTelegramUrl = ""
siteTwitterUrl = "https://twitter.com/Go7hic"
siteGithubUrl = "https://github.com/go7hic"
siteEmailUrl = "mailto:gtfx0209#####gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""