siteTitle = "Go7hic"
siteDescr = ""
siteAuthor = "Go7hic"

siteTelegramUrl = ""
siteTwitterUrl = "https://twitter.com/Go7hic"
siteGithubUrl = "https://github.com/dyygtfx"
siteEmailUrl = "mailto:admin@yongyuan.us"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""